package com.clearixam.service

import com.clearixam.analytics.AnalyticsService
import com.clearixam.repository.UserRepository
import org.springframework.stereotype.Service

@Service
class ReportService(
    private val analyticsService: AnalyticsService,
    private val userRepository: UserRepository
) {
    fun generatePerformanceReport(userEmail: String): ByteArray {
        val user = userRepository.findByEmail(userEmail)
            ?: throw IllegalArgumentException("User not found")
        val overview = analyticsService.getOverview(userEmail)
        
        val report = buildString {
            appendLine("CLEARIXAM PERFORMANCE REPORT")
            appendLine("==================================================")
            appendLine()
            appendLine("User: " + user.email)
            appendLine("Generated: " + java.time.LocalDateTime.now().toString())
            appendLine()
            appendLine("PERFORMANCE SUMMARY")
            appendLine("--------------------------------------------------")
            appendLine("Average Score: " + String.format("%.2f", overview.averageScore))
            appendLine("Moving Average: " + String.format("%.2f", overview.movingAverage))
            appendLine("Probability: " + overview.probability.toString() + "%")
            appendLine("Risk Level: " + overview.riskLevel.toString())
            
            if (overview.improvementRate != null) {
                val sign = if (overview.improvementRate >= 0) "+" else ""
                appendLine("Improvement Rate: " + sign + String.format("%.1f", overview.improvementRate) + "%")
            }
            
            if (overview.consistencyScore != null) {
                appendLine("Consistency: " + overview.consistencyScore.toString())
            }
            
            if (overview.weakSubjects.isNotEmpty()) {
                appendLine()
                appendLine("AREAS FOR IMPROVEMENT")
                appendLine("--------------------------------------------------")
                overview.weakSubjects.forEach { subject ->
                    appendLine(subject.subjectName.toString() + ": " + String.format("%.1f", subject.accuracy) + "% accuracy")
                }
            }
            
            if (overview.goalProgress != null) {
                appendLine()
                appendLine("GOAL PROGRESS")
                appendLine("--------------------------------------------------")
                appendLine("Target Score: " + String.format("%.2f", overview.goalProgress.targetScore))
                appendLine("Current Score: " + String.format("%.2f", overview.goalProgress.currentScore))
                appendLine("Progress: " + String.format("%.1f", overview.goalProgress.goalProgressPercent) + "%")
                appendLine("Days Remaining: " + overview.goalProgress.daysRemaining.toString())
                val status = if (overview.goalProgress.onTrack) "On Track" else "Needs Focus"
                appendLine("Status: " + status)
            }
            
            if (overview.recommendedAttemptRange != null && overview.strategyNote != null) {
                appendLine()
                appendLine("RECOMMENDED STRATEGY")
                appendLine("--------------------------------------------------")
                appendLine(overview.recommendedAttemptRange)
                appendLine(overview.strategyNote)
            }
            
            appendLine()
            appendLine("==================================================")
            appendLine("This report is generated by CleariXam Analytics Platform")
            appendLine("Data is securely stored and processed")
        }
        
        return report.toByteArray(Charsets.UTF_8)
    }
}
